[0m15:18:15.194793 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2C9D9A560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2CCAFAD70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2CCAFAF80>]}


============================== 15:18:15.202772 | e8a8ca3f-5b9b-44a6-8b5e-d65b9eaba1b7 ==============================
[0m15:18:15.202772 [info ] [MainThread]: Running with dbt=1.6.1
[0m15:18:15.204767 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:18:15.207759 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/HP/.dbt')}
[0m15:18:15.210752 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:18:30.574510 [debug] [MainThread]: Starter project path: C:\Users\HP\Documents\dbt-env\lib\site-packages\dbt\include\starter_project
[0m15:18:30.833936 [info ] [MainThread]: 
Your new dbt project "dbt_learn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:18:30.848392 [info ] [MainThread]: Setting up your profile.
[0m15:19:04.645249 [error] [MainThread]: Encountered an error:
list index out of range
[0m15:19:04.649227 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\HP\Documents\dbt-env\lib\site-packages\dbt\cli\requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\HP\Documents\dbt-env\lib\site-packages\dbt\cli\requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\HP\Documents\dbt-env\lib\site-packages\dbt\cli\main.py", line 468, in init
    results = task.run()
  File "C:\Users\HP\Documents\dbt-env\lib\site-packages\dbt\task\init.py", line 307, in run
    adapter = self.ask_for_adapter_choice()
  File "C:\Users\HP\Documents\dbt-env\lib\site-packages\dbt\task\init.py", line 234, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m15:19:04.651114 [debug] [MainThread]: Command `dbt init` failed at 15:19:04.651114 after 49.48 seconds
[0m15:19:04.652319 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2C9D9A560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2CCAFAB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2CCAFAEF0>]}
[0m15:19:04.653071 [debug] [MainThread]: Flushing usage events
[0m15:19:21.171385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F63270A530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F63545AD40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F63545AF80>]}


============================== 15:19:21.180563 | 6eca52bf-5286-4eb0-ae93-5625d35f654b ==============================
[0m15:19:21.180563 [info ] [MainThread]: Running with dbt=1.6.1
[0m15:19:21.184553 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m15:19:59.997471 [info ] [MainThread]: A project called dbt_learn already exists here.
[0m15:19:59.998276 [debug] [MainThread]: Command `dbt init` succeeded at 15:19:59.998276 after 38.85 seconds
[0m15:19:59.999275 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F63270A530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F62E780820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F63545AB30>]}
[0m15:20:00.000626 [debug] [MainThread]: Flushing usage events
[0m16:10:53.773898 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023805CBE530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023808A06C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023808A071C0>]}


============================== 16:10:53.780881 | 4c13e1c1-61f6-4c78-95f5-e7ba2d79d2e9 ==============================
[0m16:10:53.780881 [info ] [MainThread]: Running with dbt=1.6.1
[0m16:10:53.782876 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:10:53.783874 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HP\Documents\dbt_learn\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:10:53.786865 [debug] [MainThread]: Command `dbt run` failed at 16:10:53.785867 after 0.03 seconds
[0m16:10:53.788858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023805CBE530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023808A06B60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023808A06B30>]}
[0m16:10:53.789855 [debug] [MainThread]: Flushing usage events
[0m16:16:33.803165 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002834E43E530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002835118ED70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002835118F130>]}


============================== 16:16:33.819558 | 3c93d19d-acbb-40eb-b17f-fe667868d30c ==============================
[0m16:16:33.819558 [info ] [MainThread]: Running with dbt=1.6.1
[0m16:16:33.821553 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:16:33.822549 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HP\Documents\dbt_learn\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:16:33.824546 [debug] [MainThread]: Command `dbt test` failed at 16:16:33.823551 after 0.03 seconds
[0m16:16:33.824546 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002834E43E530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002835118EB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002835118EB60>]}
[0m16:16:33.825545 [debug] [MainThread]: Flushing usage events
